---
title: "CPESR"
author: "CPESR"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(dplyr.summarise.inform = FALSE)
knitr::opts_chunk$set(fig.asp = 9/16, fig.retina = 2)

library(tidyverse)
library(ggcpesrthemes)
library(kpiESR)
theme_set(theme_cpesr())
theme_cpesr_setup(authors = "Julien Gossa", source = "https://github.com/cpesr/RFC/")
```

## plot_SCSPvsEtu

```{r, results='asis'}
plot_SCSPvsEtu <- kpiesr_plot_line("Universités et assimilés", c("kpi.ETU.P.effectif","kpi.FIN.S.SCSP"), val="evolution") +
  ggtitle("Evolution du nombre d'étudiants et de la SCSP", subtitle="Subvention pour charge de service public - Périmètre Universités")
plot_SCSPvsEtu
```

## plot_RecettesFormation

```{r, results='asis'}
plot_RecettesFormation <- kpiesr_plot_line("Ensemble",c("kpi.ETU.P.effectif","kpi.FIN.S.recettesFormation","kpi.FIN.S.SCSP"), val="evolution") +
  ggtitle("Evolution des recettes formation vs. SCSP et nombre d'étudiants", subtitle="Droits d'inscription, DU, VAE, formation continue, taxe d'apprentissage") +
  guides(linetype="none",alpha="none",size="none")

plot_RecettesFormation

esr %>% 
  filter(Groupe == "Ensemble") %>%
  select(Rentrée, Groupe, kpi.FIN.S.recettesFormation, kpi.K.forPetu) %>%
  spoiler_table("RecettesFormation",trim = Inf)
```

## plot_RessourcesPropres

```{r, results='asis'}
plot_RessourcesPropres <- kpiesr_plot_line("Ensemble",c("kpi.ETU.P.effectif","kpi.FIN.S.recettesFormation","kpi.FIN.S.recettesRecherche","kpi.FIN.S.SCSP"), val="evolution") +
  ggtitle("Evolution des recettes propres vs. SCSP et nombre d'étudiants", subtitle="Droits d'inscription, DU, VAE, formation continue, taxe d'apprentissage / ANR, ERC, contrats de recherche") +
  guides(linetype="none",alpha="none",size="none")

plot_RessourcesPropres

esr %>% 
  filter(Groupe == "Ensemble") %>%
  select(Rentrée, Groupe, kpi.FIN.S.recettesFormation, kpi.K.forPetu, kpi.FIN.S.recettesRecherche, kpi.K.recPect) %>%
  spoiler_table("RecettesFormation",trim = Inf)
```

## plot_SCSPvsMS

```{r, results='asis'}
plot_SCSPvsMS <- kpiESR::esr %>%
  filter(Etablissement == "Universités et assimilés", Rentrée > 2008) %>%
  mutate(diff = kpi.FIN.S.SCSP-kpi.FIN.S.masseSalariale) %>% 
  ggplot(aes(x=Rentrée+1,y=diff)) +
  geom_hline(yintercept = 1) +
  geom_line(size=1, color="darkorange") + geom_point(shape = 21, stroke=2,size=2,fill="white",color="darkorange") +
  scale_x_continuous(breaks = scales::pretty_breaks(12)) +
  scale_y_continuous(labels = ~ paste(.x/1e6,"M€"), name = "SCSP-MS") +
  scale_color_distiller(palette="Reds") +
  theme(legend.position = "None", panel.grid.minor.x = element_blank()) +
  labs(
    title="Différence entre SCSP et masse salariale des universités",
    x="Année") 
plot_SCSPvsMS
```

## plot_MassificationRecent

```{r}
plot_MassificationRecent <- read.csv("kh-sl_eleves_sup.csv") %>%
  filter(champ_geo!="") %>%
  filter(annee >= 2000) %>%
  mutate(champ_geo = factor(champ_geo,levels=unique(champ_geo))) %>%
  filter(!is.na(disc_total)) %>%
  ggplot(aes(x=annee,y=disc_total, color = champ_geo)) +
  annotate("rect", xmin = 2000, xmax = 2021, ymin = 1.3e6, ymax = 1.7e6, color="black", fill=NA) +
  geom_line(size = 1) +
  scale_y_continuous(labels = ~ paste(.x/1e6,"M"), name = "Effectif") +
  scale_color_discrete(name = "Périmètre") +
  ggtitle("Evolution des effectifs étudiants du MESR") +
  theme(legend.position = "bottom") + 
  guides(color=guide_legend(nrow = 2)) +
  cpesr_cap(author = "Julien Gossa et Kévin Hédé", source="Données collectées par Kevin Hédé") 
plot_MassificationRecent
```

## plot_MassificationLong


```{r}
plot_MassificationLong <- read.csv("kh-sl_eleves_sup.csv") %>%
  filter(champ_geo!="") %>%
  mutate(champ_geo = factor(champ_geo,levels=rev(unique(champ_geo)))) %>%
  filter(!is.na(disc_total)) %>%
  ggplot(aes(x=annee,y=disc_total, color = champ_geo)) +
  annotate("rect", xmin = 2000, xmax = 2021, ymin = 1.3e6, ymax = 1.7e6, color="black", fill=NA) +
  geom_line(size = 1) +
  scale_y_continuous(labels = ~ paste(.x/1e6,"M"), name = "Effectif") +
  scale_color_discrete(name = "Périmètre") +
  ggtitle("Evolution des effectifs étudiants du MESR") +
  theme(legend.position = "bottom") + 
  guides(color=guide_legend(nrow = 2)) +
  cpesr_cap(author = "Julien Gossa et Kévin Hédé", source="Données collectées par Kevin Hédé") 
plot_MassificationLong
```

## plot_LvsM

```{r, fig.asp=7/16, fig.width=7, out.width="100%", fig.align='center'}
load(file="sise.RData")

plot_LvsM <- sise %>%
  group_by(Rentrée,Niveau = paste(LMD, substr(NIVEAU,2,2), sep="")) %>%
  summarise(Etudiants = sum(Etudiants)) %>%
  filter(Niveau %in% c("L3","M1")) %>%
  mutate(Rentrée = ifelse(Niveau == "L3", Rentrée+1,Rentrée)) %>%
  filter(Rentrée != 2012, Rentrée != 2023) %>%
  ggplot(aes(x=Rentrée, y= Etudiants, color=Niveau)) +
  geom_line(linewidth = 1.5) + geom_point(shape = 21, stroke = 2, size = 2, fill="white") + 
  scale_x_continuous(labels = ~ paste0("L3 ", .x-1,"\nM1 ",.x), breaks = seq(2011,2030,2), name="Cohorte") +
  scale_y_continuous(labels = ~ paste0(.x/1e3,"k"), name = "Inscriptions étudiantes") +
  ggtitle("Etudiant⋅e⋅s  inscrit⋅e⋅s en L3 à l'année N et M1 à l'année N+1" )

plot_LvsM
```

## plot_postesMCF

```{r, out.width="90%", fig.align="center"}
emplois.ec <- read.csv2("cpesr-emplois-ec.csv")

plot_postesMCF <- emplois.ec %>% 
  filter(Périmètre.ID %in% c("Ensemble","ST","LLASHS","DEG")) %>%
  mutate(Périmètre.label=factor(Périmètre.label, 
        levels=c("Ensemble","Sciences et techniques","Lettres et sciences humaines","Droit éco gestion"))) %>%
  mutate(Concours.NonPourvus.MCF = Concours.Postes.MCF - Concours.Recrutés.MCF) %>%
  ggplot(aes(x=Année, y=Concours.Postes.MCF, color=Périmètre.label)) +
  geom_line(linewidth = 1) + geom_point(shape = 21, stroke = 1.5, size = 1.5, fill="white") +
  scale_x_continuous(breaks = scales::pretty_breaks(12)) +
  labs(title="Concours MCF : Postes ouverts", 
       y = "Nombre de postes") 
plot_postesMCF
```

## plot_postesMCFvsCandidats

```{r, out.width="90%", fig.align="center"}
plot_postesMCFvsCandidats <- emplois.ec %>% 
  filter(Périmètre.ID == "Ensemble") %>%
  mutate(Concours.NonPourvus.MCF = Concours.Postes.MCF - Concours.Recrutés.MCF) %>%
  pivot_longer(cols=c(Concours.Postes.MCF,Concours.Candidats.MCF), names_to = "Série", values_to = "Valeur") %>%
  mutate(Série = factor(Série, 
                        levels=c("Concours.Postes.MCF","Concours.Candidats.MCF"),
                        labels=c("Postes MCF","Candidats") )) %>%
  filter(Année > 2014, Année < 2024) %>%
  mutate(Valeur100 = Valeur/first(Valeur)*100, .by=Série) %>%
  ggplot(aes(x=Année, y=Valeur100, color=Série)) +
  geom_line(linewidth = 1) + geom_point(shape = 21, stroke = 1.5, size = 1.5, fill="white") +
  scale_x_continuous(breaks = scales::pretty_breaks(12)) +
  scale_color_brewer(palette="Set1", direction = -1) +
  labs(title="Concours MCF : Postes ouverts et nombre de candidats", 
       y = "Valeur 100 en 2015") 
plot_postesMCFvsCandidats
```

## plot_postesMCFnonPourvus

```{r, out.width="90%", fig.align="center"}
plot_postesMCFnonPourvus <- emplois.ec %>% 
    filter(Année > 2014, Année < 2024) %>%
  filter(Périmètre.ID %in% c("Ensemble","ST","LLASHS","DEG","27")) %>%
  mutate(Périmètre.label=factor(Périmètre.label, 
        levels=c("Ensemble","Sciences et techniques","Lettres et sciences humaines","Droit éco gestion","Informatique"))) %>%
  ggplot(aes(x=Année, y=kpi.MCF.TauxPostesNonPourvus, color=Périmètre.label)) +
  geom_line(linewidth = 1) + geom_point(shape = 21, stroke = 1.5, size = 1.5, fill="white") +
  scale_x_continuous(breaks = scales::pretty_breaks(12)) +
  scale_y_continuous(labels = scales::percent) +
  labs(title="Concours MCF : Taux de postes non pourvus", 
       y = "Taux de postes non pourvus") 
plot_postesMCFnonPourvus
```


## plot_BMO

```{r}
bmo <- read.csv2("Besoins en Main-d’Œuvre_Top 10 en nombre de projets de recrutement non saisonniers en 2024 par Métie.csv", skip = 3) %>%
  mutate(Projets.de.recrutement.non.saisonniers = as.numeric(gsub(" ","",Projets.de.recrutement.non.saisonniers))) %>%
  mutate(Voie = factor(case_when(
    startsWith(Métier,"Inf") ~ "Formation supérieure de santé",
    TRUE ~ "Formation professionnelle"
  ),
  levels = c("Formation professionnelle","Formation supérieure de santé","Formation universitaire","Formation d'ingénieur"),
  labels = c("Formation professionnelle","Formation supérieure de santé","Formation universitaire","Formation d'ingénieur")))
  

plot_bmo <- bmo  %>%
  ggplot(aes(x=Projets.de.recrutement.non.saisonniers,
             y=reorder(str_wrap(Métier,40),Projets.de.recrutement.non.saisonniers),
             fill = Voie)) +
  geom_col(show.legend = TRUE) +
  scale_x_continuous(labels = scales::number) +
  scale_fill_brewer(palette = "Dark2", drop=FALSE,guide = guide_legend(nrow = 2)) +
  labs(title = "Top 10 des métiers les plus demandés en 2024",
       x = "Nombre de projets de recrutement non saisonniers",
       y = NULL) +
  theme(legend.position = "top")

plot_bmo
```

### Massification (1960-2000) : Investissements massifs dans l'éducation

```{r diplome, cache = TRUE}
load("emploi.RData")

#Graphique pour connaître le niveau de diplome des jeunes selon l'année civile 
plot_diplome <- function(agemin = 15, agemax = 30, anneemin = 1971, anneemax = 2020) {
  emploi %>%
    filter(Age > agemin, Age < agemax, Annee >= anneemin, Annee <= anneemax) %>%
    mutate(Diplome = factor(Diplome,
                            levels=c("Bac+5","Bac+3","Bac+2","Bac","CAP-BEP","DNB","Aucun"))) %>%
    mutate(Diplome = fct_recode(Diplome,
                                Tertiaire = "Bac+5",
                                Tertiaire = "Bac+3",
                                Tertiaire = "Bac+2",
                                Secondaire = "Bac",
                                Secondaire = "CAP-BEP",
                                Secondaire = "DNB",
                                Primaire = "Aucun") ) %>% 
    group_by(Annee,Diplome) %>%
    summarise(Population = sum(Population)/1e6) %>%
    ungroup() %>%
    na.omit() %>%
    filter(Annee != 1973) %>%
    complete(Annee,Diplome,fill=list(Population = 0)) %>%
    ggplot(aes(x=Annee,y=Population,fill=Diplome,group=Diplome)) +
    geom_area(color="white", alpha=0.6, position = "fill") + 
    #geom_vline(xintercept = c(1994,2007)) +
    xlab("Année")
}

plot_stratification_continu <- plot_diplome(agemin = 25, agemax = 30) +
  scale_y_continuous(labels = scales::percent, name = "Part des jeunes de 25 à 30 ans") +
  cpesr_cap(authors = "Camille Schumacher et Julien Gossa", source = "Enquête emploi INSEE")

plot_stratification_continu
```


### Massification (1960-2000) : Investissements massifs dans l'éducation


```{r diplome.2, cache = TRUE}
#Graphique pour connaître le niveau de diplome des jeunes selon l'année civile 
plot_categorie_ponctuel <- function(categorie="Activite", agemin = 15, agemax = 30, anneemin = 1971, anneemax = 2020, fill=TRUE, keep_na=FALSE) {
  if(fill) {
    position_geom <- "fill"
    label_scale <- ~ scales::percent(abs(.x))
    title_y <- "Pourcentage de la population 25-30"
  } else {
    position_geom <- "stack"
    label_scale <- function(x) x/1e6
    title_y <- "Effectif (millions)"
  }
  
  emploi %>%
    filter(Age >= agemin, Age <= agemax, Annee %in% c(anneemin,anneemax)) %>%
        mutate(Diplome = factor(Diplome,
                            levels=c("Bac+5","Bac+3","Bac+2","Bac","CAP-BEP","DNB","Aucun"))) %>%
    mutate(Diplome = fct_recode(Diplome,
                                Tertiaire = "Bac+5",
                                Tertiaire = "Bac+3",
                                Tertiaire = "Bac+2",
                                Secondaire = "Bac",
                                Secondaire = "CAP-BEP",
                                Secondaire = "DNB",
                                Primaire = "Aucun") ) %>% 
    mutate(Diplome = fct_rev(Diplome)) %>%
    group_by(Annee, Sexe, Categorie=!!as.name(categorie)) %>%
    summarise(Population = sum(Population, na.rm=TRUE)) %>%
    { if (!keep_na) na.omit(.) else . } %>%
    { if (fill) group_by(.,Annee) %>% mutate(Population = Population / sum(Population)) else . } %>%
    ungroup() %>%
    complete(Annee, Categorie, fill = list(Population = 0)) %>% 
    mutate(Population = ifelse(Sexe == "H",-Population,Population)) %>%
    ggplot(aes(y=Categorie,x=Population,fill=Sexe, group=Sexe)) +
    geom_col(alpha=0.8, color="white",width = 1) + 
    expand_limits(x=c(-0.28,0.28)) +
    facet_grid(.~Annee) +
    scale_x_continuous(labels = label_scale) +
    scale_fill_brewer(palette = "Set2") +
    labs (y = "Diplôme", x = title_y, caption = "Source :Enquête Emploi (1971 - 2020)")
}


plot_stratification_ponctuel <- plot_categorie_ponctuel(categorie="Diplome", agemin = 25, agemax = 30) +
  #scale_y_continuous(labels = scales::percent, name = "Part des jeunes de 25 à 30 ans") +
  cpesr_cap(authors = "Camille Schumacher et Julien Gossa", source = "Enquête emploi INSEE")

plot_stratification_ponctuel
```


## Save

```{r}
save(plot_SCSPvsEtu,
     plot_RecettesFormation, 
     plot_RessourcesPropres,
     plot_SCSPvsMS,
     plot_MassificationRecent,
     plot_MassificationLong,
     plot_LvsM,
     plot_postesMCF,
     plot_postesMCFvsCandidats,
     plot_postesMCFnonPourvus,
     plot_bmo,
     plot_stratification_continu,
     plot_stratification_ponctuel,
     file = "plots.RData")
```
