---
title: "Démonstration PMP"
author: "Julien Gossa"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
options(dplyr.summarise.inform = FALSE)
knitr::opts_chunk$set(fig.asp = 9/16, fig.retina = 2)

library(tidyverse)
library(ggcpesrthemes)
theme_set(theme_cpesr())
theme_cpesr_setup(authors = "Julien Gossa", source = "https://github.com/cpesr/RFC/")

library(kpiESR)
```


```{r, results='asis'}
kpiesr_plot_line("Ensemble", c("kpi.ETU.P.effectif","kpi.FIN.P.ressources","kpi.K.resPetu"), val="evolution") +
  ggtitle("Evolution du nombre d'étudiants et du budget des établissements", subtitle="Périmètre MESR") +
  guides(linetype = "none", alpha = "none", size="none")
```

```{r, results='asis'}
kpiESR::esr %>%
  filter(Groupe == "Ensemble") %>%
  select(Groupe,Rentrée,kpi.ETU.P.effectif,kpi.FIN.P.ressources,kpi.K.resPetu) %>%
  spoiler_table(trim = Inf)
```


```{r scsp.vs.ms2}
kpiESR::esr %>%
  filter(pid=="Ensemble", Rentrée > 2008) %>%
  #filter(pid=="Ensemble", Rentrée > 2008) %>%
  mutate(diff = kpi.FIN.S.SCSP-kpi.FIN.S.masseSalariale) %>% 
  mutate(Exercice = Rentrée + 1) %>%
  ggplot(aes(x=Exercice,y=diff, fill=diff)) +
  geom_hline(yintercept = 0) +
  geom_col(color="black") +
  scale_x_continuous(breaks = seq(2010,2025)) +
  scale_y_continuous(labels = ~ paste(.x/1e6,"M€"), name = "SCSP-MS") +
  scale_fill_distiller(palette="RdBu", direction = 0, limits = c(-1.3e9,1.3e9)) +
  ggtitle("Différence entre SCSP et masse salariale des établissements du MESR") +
  theme(legend.position = "None", panel.grid.minor.x = element_blank())
```

```{r, results='asis'}
kpiESR::esr %>%
  filter(pid=="Ensemble", Rentrée > 2008) %>%
  mutate(Exercice = Rentrée + 1) %>%
  select(Exercice, kpi.FIN.S.SCSP, kpi.FIN.S.masseSalariale) %>%
  mutate(diff = kpi.FIN.S.SCSP-kpi.FIN.S.masseSalariale) %>% 
  spoiler_table(trim = Inf)
```



```{r, results='asis'}
kpiesr_plot_line("Ensemble", c("kpi.FIN.S.SCSP","kpi.FIN.S.recettesFormation","kpi.FIN.S.recettesRecherche"), val="evolution") +
  ggtitle("Evolution de la SCSP et des recettes propres formation et recherche", subtitle="Subvention pour charge de service public - Périmètre MESR") +
  guides(linetype = "none", alpha = "none", size="none")
```


```{r, results='asis'}
kpiESR::esr %>%
  filter(Groupe == "Ensemble") %>%
  select(Groupe,Rentrée,kpi.FIN.S.SCSP,kpi.FIN.S.recettesRecherche,kpi.FIN.S.recettesFormation, kpi.K.forPetu) %>%
  spoiler_table(trim = Inf)
```



```{r, results='asis'}
kpiesr_plot_line("Ensemble", c("kpi.ENS.P.effectif","kpi.ENS.S.titulaires", "kpi.BIA.P.effectif","kpi.BIA.S.titulaires"), val="valeur") +
  ggtitle("Evolution du nombre d'étudiants et de la SCSP", subtitle="Subvention pour charge de service public - Périmètre MESR") +
  guides(linetype = "none", alpha = "none", size="none") +
  xlim(2012,2024)
```

```{r, results='asis'}
kpiesr_plot_line("Ensemble", c("kpi.ENS.P.effectif","kpi.ENS.S.titulaires", "kpi.BIA.P.effectif","kpi.BIA.S.titulaires"), val="evolution") +
  ggtitle("Evolution du nombre d'étudiants et de la SCSP", subtitle="Subvention pour charge de service public - Périmètre MESR") +
  guides(linetype = "none", alpha = "none", size="none") 
```

```{r, results='asis'}
esr.pnl %>% 
  filter(pid == "Ensemble") %>%
  filter(kpi %in% c("kpi.ENS.P.effectif","kpi.ENS.S.titulaires", "kpi.ENS.S.contractuels", "kpi.BIA.P.effectif","kpi.BIA.S.titulaires")) %>%
  select(kpi, Rentrée, valeur, evolution) %>%
  filter(!is.na(valeur)) %>%
  arrange(kpi, Rentrée) %>%
  spoiler_table(trim=Inf)
```

```{r, results='asis'}
kpiesr_plot_line("Ensemble", c("kpi.ENS.S.titulaires","kpi.ETU.P.effectif","kpi.K.ensPetu"), val="evolution") +
  ggtitle("Evolution du nombre d'étudiants et de la SCSP", subtitle="Subvention pour charge de service public - Périmètre MESR") +
  guides(linetype = "none", alpha = "none", size="none") 
```


```{r scsp.vs.ms3}
kpiESR::esr %>%
  filter(Groupe=="Universités et assimilés", Rentrée == 2024) %>%
  left_join(kpiESR::esr.etab) %>%
  mutate(PerimEx = ifelse(PerimEx=="","NINI", PerimEx)) %>%
  mutate(diff = kpi.FIN.S.SCSP-kpi.FIN.S.masseSalariale) %>% 
  mutate(Exercice = Rentrée + 1) %>%
  ggplot(aes(x=kpi.ETU.P.effectif, y=diff, size=kpi.FIN.P.ressources, color=PerimEx, shape=PerimEx)) +
  geom_hline(yintercept = 0) +
  ggrepel::geom_text_repel(aes(label=Sigle), 
                           size=3, color="grey") +
  geom_point() +
  scale_x_continuous(labels = ~ paste(.x/1e3,"k"), name = "Effectif étudiants") +
  scale_y_continuous(labels = ~ paste(.x/1e6,"M€"), name = "SCSP-MS") +
  scale_size_continuous(labels = ~ paste(.x/1e6,"M€"), name = "Budget") +
  ggtitle("Taille et différence entre SCSP et masse salariale des universités", subtitle="En fonction de leur budget et de leur périmètre d'excellence, sur l'année 2024-2025") +
  theme(legend.position = "right", panel.grid.minor.x = element_blank()) +
  guides(color = guide_legend(override.aes = list(size = 4)))
```

```{r scsp.vs.ms4}
kpiESR::esr %>%
  filter(Groupe=="Universités et assimilés", Rentrée == 2024) %>%
  left_join(kpiESR::esr.etab) %>%
  mutate(PerimEx = ifelse(PerimEx=="","NINI", PerimEx)) %>%
  mutate(taux = kpi.FIN.S.SCSP/kpi.FIN.S.masseSalariale) %>% 
  filter(taux < 1.5, taux > 0.6) %>%
  mutate(Exercice = Rentrée + 1) %>%
  ggplot(aes(x=kpi.ETU.P.effectif, y=taux, size=kpi.FIN.P.ressources, color=PerimEx, shape=PerimEx)) +
  geom_hline(yintercept = 1) +
  geom_point() +
  ggrepel::geom_text_repel(aes(label=Sigle), 
                           size=3, color="grey") +
  scale_x_continuous(labels = ~ paste(.x/1e3,"k"), name = "Effectif étudiants") +
  #scale_y_continuous(labels = ~ paste(.x/1e6,"M€"), name = "SCSP-MS") +
  scale_size_continuous(labels = ~ paste(.x/1e6,"M€"), name = "Budget") +
  ggtitle("Différence entre SCSP et masse salariale des universités", subtitle="En fonction de leur taille et de leur périmètre d'excellence") +
  theme(legend.position = "right", panel.grid.minor.x = element_blank()) +
  guides(color = guide_legend(override.aes = list(size = 4)))
```


```{r}
kpiesr_plot_map(rentrée = 2023, id = "None", groupe = "Universités et assimilés", xvar = "kpi.K.forPetu", yvar = "kpi.K.ensPetu") +
  labs(
    title = "Recettes formation par étudiant et taux d'encadrement pédagogique",
    subtitle = "des universités, en 2023-2024",
    x = "Recettes formation par étudiant (€)",
    y = "Taux d'encadrement pédagogique\n(ens. / 100 étu.)"
  ) +
  theme(legend.position="right")
```
